site_name: Data Engineering Works
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli

repo_url: https://github.com/manish-chet/DataEngineering
repo_name: "DataEngineering"
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  favicon: assets/images/sqldeveloper-original.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Projects: projects/README.md
  - Kafka:
          - Overview: kafka/kafka.md
          - Installation:
              - With ZooKeeper: kafka/kafka_install_zookeeper.md
              - With KRaft: kafka/kafka_install_kraft.md
          - Study Material: kafka/kafka_study_material.md          
  - Airflow:
          - Overview: airflow/index.md
          - Installation: airflow/airflow_install_onpremise.md
          - Maintaneance: airflow/airflow_maintaneance.md
          - Study Material: airflow/airflow_study_material.md
  - Kubernetes:
          - Overview: devops/kubernetes_overview.md
          - Installation: devops/kubernetes_install.md
  - Data Engineering:
          - Overview: DataEngineering/DataEngineering.md
          - Data Engineering Lifecycle: DataEngineering/DEcycle.md
          - Data Engineering UnderCurrents: DataEngineering/DEundercurrent.md     
  - About Me: about.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.mark
  - attr_list

extra_javascript:
  - https://unpkg.com/mermaid@9.1.3/dist/mermaid.min.js
