site_name: Data Engineering Works
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli

repo_url: https://github.com/manish-chet/DataEngineering
repo_name: "DataEngineering"
edit_uri: edit/main/docs/


copyright: >
  Copyright &copy; 2025 Manishkumar Chetpalli

theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  favicon: assets/images/sqldeveloper-original.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - navigation.footer  
    - content.action.feedback 
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Hadoop: 
      - Big Data Overview: hadoop/Bigdata.md
      - Hadoop Concepts: hadoop/HadoopArchitecture.md
      - Hadoop HA Architecture: hadoop/HadoopHA.md
      - MapReduce Concepts: hadoop/mapreduce.md
      - YARN Concepts: hadoop/yarn.md
      - Kerberos Concepts: hadoop/kerberos.md
  - Ignite:
      - Ignite Overview: ignite/ignite.md
      - Caching topology: ignite/ignite2.md
      - Caching strategy: ignite/ignite3.md
      - CAP Theorem and Where Does Ignite Stand: ignite/ignite4.md
      - Zero SPOF: ignite/ignite5.md
      - How SQL Queries Work in Ignite: ignite/ignite6.md
      - Expiration & Eviction of Cache Entries in Ignite: ignite/ignite7.md
      - Discovery and communication mechanisms: ignite/ignite8.md
      - Setup & Install: ignite/igniteinstall.md
  - Hive:
      - Hive Overview: hive/hive.md
      - Hive SerDe: hive/hive2.md
      - Partitioning & Bucketing: hive/hive3.md
      - Joins in Hive: hive/hive4.md
  - Kafka:
    - Concepts:
        - Overview: kafka/kafka.md
        - Architecture: kafka/kafkaarch.md
        - Concepts: kafka/kafka concepts.md
        - Role of Zookeeper in Kafka: kafka/kafkazk.md
        - Offsets: kafka/offsets.md
        - Producers: kafka/producer.md
        - Consumers: kafka/consumer.md
        - KB-ZK Setup & Install: kafka/kafka_install_zookeeper.md
        - MySQL to Kafka to JSON Files: kafka/mysqlkafka.md
  - Airflow:
      - Airflow Overview: airflow/airflow.md
      - Airflow Installation: airflow/airflow_install_onpremise.md
      - Airflow Maintaneance DAGs: airflow/airflow_maintaneance.md
  - Spark:
      - Spark Overview: spark/spark.md
      - Spark Ecosystem: spark/sparkecosystem.md
      - Resilient Distributed Datasets (RDD) in Spark: spark/Rdd.md
      - How Spark Perform Data Partitioning?: spark/spark2.md
      - Transformations & Actions : spark/sparktrans.md
  - Devops:
      - Kubernetes Architecture Explained: devops/kubernetesarchitecture.md
      - Kubernetes Installation: devops/kubernetes_install.md
      - Kubernetes Labels, Selectors, and Replication Controllers: devops/kube2.md
      - Kubernetes Jobs,init container and pod lifecycle: devops/kube3.md
      - Deploying object in Kubernetes: devops/kube4.md
      - Kubernetes Networking: devops/kube5.md
      - Kubernetes Persistent Volumes & Liveness Probes: devops/kube6.md
      - Kubernetes Namespaces & Resource Quotas: devops/kube7.md
      - KubernetesHorizontal Pod Autoscaling: devops/kube8.md
      - Git: devops/git.md
  - Data Engineering:
      - Data Engineering Overview: DataEngineering/DataEngineering.md
      - Data Engineering Lifecycle: DataEngineering/DEcycle.md
      - Data Engineering UnderCurrents: DataEngineering/DEundercurrent.md
      - Good Data Architecture: DataEngineering/DesigningGDA.md
  - SQL: sql/sql.md
  - NoSQL: 
      - Overview: sql/Mongo.md
      - MongoDB: sql/mongo2.md
  - Tooling & setup:
      - Jupyternotebok and JupyteHhub: tooling/jupyter_setup.md
      - Postgres HA: tooling/postgresHA.md
  - About Me: about.md
  
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.mark
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manishkumarchetpalli/
    - icon: fontawesome/brands/github
      link: https://github.com/manish-chet


extra_css:
  - stylesheets/extra.css
