site_name: Data Engineering Works
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli

theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Projects: projects.md
  - Big Data:
      - Apache Kafka:
          - Overview: bigdata/kafka.md
          - Installation:
              - With ZooKeeper: bigdata/kafka/kafka_install_zookeeper.md
              - With KRaft: bigdata/kafka/kafka_install_kraft.md
      - Apache Airflow:
          - Overview: bigdata/airflow/index.md
          - Installation: bigdata/airflow/airflow_install_onpremise.md
  - About Me: about.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.mark
  - attr_list

extra_javascript:
  - https://unpkg.com/mermaid@9.1.3/dist/mermaid.min.js
