site_name: Data Engineering Works
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli

repo_url: https://github.com/manish-chet
repo_name: "DataEngineering"
edit_uri: edit/main/docs/


copyright: >
  Copyright &copy; 2025 Manishkumar Chetpalli

theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  favicon: assets/images/sqldeveloper-original.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - search.share
    - navigation.footer  
    - content.action.feedback 
    - toc.follow
    - toc.extend
  palette:
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Projects:
    - List of Projects: projects/readme.md
    - FastAPI Kafka Producer: projects/kafkaapi.md
    - Flink-Ignite Custom Dialect: projects/flink-ignite.md
  - Setup Docs:
    - Jupyter Notebook and JupyterHub: tooling/jupyter_setup.md
    - Postgres HA : tooling/postgresHA.md
    - Ignite Multi Node: ignite/igniteinstall.md
    - Kafka Multi Node SASL_SSL: kafka/kafka_install_zookeeper.md
    - Airflow Multi Node: airflow/airflow_install_onpremise.md
    - Kubernetes Installation: devops/kubernetes_install.md
  - Fundamentals:
      - Overview: DataEngineering/DE.md
      - Data Engineering Lifecycle: DataEngineering/DEcycle.md
      - Data Engineering UnderCurrents: DataEngineering/DEundercurrent.md
      - Data Architecture & Design: DataEngineering/DesigningGDA.md
      - Data Orchestration: airflow/dataorchestration.md
      - File Formats: DataEngineering/fileformat.md
      - SQL:
        - SQL Overview: sql/sql.md
        - SQL Data Types: sql/datatype.md
        - Types of commands in SQL: sql/typeofcommands.md
        - SQL Constraints: sql/constraints.md
        - SQL Functions: sql/functions.md
        - SQL Joins: sql/joins.md
        - SQL Views: sql/views.md
        - SQL Window Functions: sql/window.md
        - SQL Frame clause: sql/frame.md
        - SQL CTE: sql/cte.md
        - SQL Subqueries: sql/subq.md
        - SQL Indexing: sql/index.md
        - SQL Optimizations: sql/optimize.md
  - BigData:  
      - Overview: hadoop/Bigdata.md
      - HDFS:  hadoop/HDFS.md
      - MapReduce: hadoop/mapreduce.md
      - YARN: hadoop/yarn.md
      - Kerberos: hadoop/kerberos.md
      - Hive:
        - Overview: hive/overview.md
        - SerDe: hive/serde.md
        - Partitioning & bucketing: hive/partition.md
        - Joins: hive/join.md
      - Kafka: 
        - Overview: kafka/overview.md
        - Architecture: kafka/architecture.md
        - Role of Zookeeper: kafka/zookeeper.md
        - Partitions & Replciations: kafka/partition.md
        - Offsets: kafka/offsets.md
        - Log segments: kafka/logsegments.md
        - Producers: kafka/producer.md
        - Handling Producer Failures: kafka/failures.md
        - Consumers: kafka/consumer.md
        - Index & Timeindex: kafka/time.md
        - Unclean Leader Election & Availability vs Durability Trade-Off: kafka/trade.md
      - Ignite: ignite/ignite.md
      - Airflow: airflow/airflow.md
      - Spark: 
        - Spark Overview: spark/overview.md
        - Spark Architecture: spark/sparkarchitecture.md
        - Transformations & Actions: spark/sparktrans.md
        - DAG: spark/DAG.md
        - SparkSQL Engine: spark/sparksqlengine.md
        - Resilient Distributed Datasets: spark/Rdd.md
        - Partition & Bucketing: spark/partition.md
        - SparkSession vs SparkContext: spark/context.md
        - Job, Stage, Task: spark/job.md
        - Repartition vs Coalesce: spark/repart.md
        - Spark Deployment Modes: spark/deploymentmode.md
        - Persist and Caching: spark/spark3.md
        - Data Skewness: spark/skew.md
        - Salting: spark/salting.md
        - RDD, Dataframe and Dataset: spark/diff2.md
        - Spark Submit: spark/submit.md
        - Memory management: spark/memory.md
        - How to process 1 TB of data in Apache Spark: spark/data.md
        - Broadcast and Accumulators in Spark: spark/broadcast.md
        - Handling Failure: spark/handling.md
        - Code Level and Resource Level Optimizations in Spark: spark/optimize.md
        - Best practices to design Spark application: spark/bp.md
        - SparkExample: spark/sparkexample.md
        - SparkExample: spark/Untitled.md
        - Notebook: spark/Untitled.py
      - Mongo: sql/Mongo.md
  - DevOps:
      - Git: devops/git.md
      - Docker: devops/docker.md
      - Kubernetes:
        - Architecture: devops/kubernetesarchitecture.md
        - Labels, Selectors, and Replication Controllers: devops/kube2.md
        - Jobs, init container and pod lifecycle: devops/kube3.md
        - Deploying object: devops/kube4.md
        - Networking: devops/kube5.md
        - Persistent Volumes & Liveness Probes: devops/kube6.md
        - Namespaces & Resource Quotas: devops/kube7.md
        - Horizontal Pod Autoscaling: devops/kube8.md
  - Interview Prep:
    - Hadoop : hadoop/hadoopiq.md
    - Hadoop Scenario based: hadoop/hadoopscenarios.md
    - Kafka : kafka/iq.md
    - Airflow : airflow/airflowiq.md
    - Flink  : flink/iq.md
    - MongoDB : sql/mongoiq.md
  - About Me: about.md
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manishkumarchetpalli/
    - icon: fontawesome/brands/github
      link: https://github.com/manish-chet

plugins:
  - mkdocs-jupyter
extra_css:
  - stylesheets/extra.css

