site_name: Data Engineering Works
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli

repo_url: https://github.com/manish-chet/DataEngineering
repo_name: "DataEngineering"
edit_uri: edit/main/docs/


copyright: >
  Copyright &copy; 2025 Manishkumar Chetpalli

theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  favicon: assets/images/sqldeveloper-original.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - navigation.footer  
    - content.action.feedback 
    - toc.follow
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Apache Projects: 
      - Overview: apache.md
      - Apache Ignite: 
          - Architecture Deep Dive: ignite/ignite.md
          - Installation: ignite/igniteinstall.md
      - Apache Kafka:
          - Kafka With ZooKeeper: kafka/kafka_install_zookeeper.md     
      - Airflow:
          - Airflow Installation: airflow/airflow_install_onpremise.md
          - Airflow Maintaneance DAGs: airflow/airflow_maintaneance.md
          - Airflow LDAP integration: airflow/airflow_ldap.md
  - Kubernetes:
      - Kubernetes Architecture Explained: devops/kubernetesarchitecture.md
      - Kubernetes Installation: devops/kubernetes_install.md
  - Data Engineering:
      - Data Engineering Overview: DataEngineering/DataEngineering.md
      - Data Engineering Lifecycle: DataEngineering/DEcycle.md
      - Data Engineering UnderCurrents: DataEngineering/DEundercurrent.md  
      - Good Data Architecture: DataEngineering/DesigningGDA.md
      - Data Engineering Roadmap: DataEngineering/roadmap.md
  - Tooling & setup: 
      - Jupyternotebok and JupyteHhub: tooling/jupyter_setup.md
      - Postgres HA: tooling/postgresHA.md
  - Interview Prep:
      - Kafka IQs: kafka/kafkaiq.md
      - Airflow IQs: airflow/airflowiq.md 
      - Hadoop IQs: hadoop/hadoop_iq.md
  - About Me: about.md
  
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.mark
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manishkumarchetpalli/
    - icon: fontawesome/brands/github
      link: https://github.com/manish-chet


extra_css:
  - stylesheets/extra.css
