name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mkdocs-site .

      - name: Generate site
        run: |
          docker run --rm -v $(pwd):/site mkdocs-site mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site 